[project]
name = "study-learning-reflex-frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.24.0",
    "python-dotenv>=1.2.1",
    "reflex>=0.8.27",
]
